import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

# Setup paths relative to repository root
GLUE_SCRIPTS_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.append(str(GLUE_SCRIPTS_DIR / "src"))

from chucaw_preprocessor.ecmwf import load_merged_dataset, serialize_parquet_chunked


def main() -> int:
    print("=============================================================")
    print("STARTING FOURCASTNET LOCAL SMOKE TEST PIPELINE")
    print("=============================================================")

    grib_path = GLUE_SCRIPTS_DIR / "data/gribs/20260331060000-6h-scda-fc.grib2"
    output_dir = GLUE_SCRIPTS_DIR / "data/fourcastnet_tensor_smoke_20260331_12z"
    raw_parquet_dir = GLUE_SCRIPTS_DIR / "data/test_data"
    raw_parquet_path = raw_parquet_dir / "20260331060000-6h-scda-fc.parquet"

    # 1. Clean and create output directories
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    raw_parquet_dir.mkdir(parents=True, exist_ok=True)

    print(f"Input GRIB: {grib_path}")
    print(f"Output Directory: {output_dir}")
    print(f"Raw Parquet Path: {raw_parquet_path}")

    # 2. Run GRIB to Parquet Conversion (Silver Layer)
    try:
        print("\n--- STAGE 1: GRIB to Raw Parquet ---")
        print("Loading merged GRIB dataset using xarray + cfgrib...")
        ds = load_merged_dataset(str(grib_path))
        print("Serializing raw parquet chunked...")
        serialize_parquet_chunked(
            ds,
            output_path=str(raw_parquet_path),
            date_str="20260331",
            run_str="12z",
        )
        print("Stage 1 completed successfully.")
    except Exception as exc:
        print(f"Stage 1 failed: {exc}", file=sys.stderr)
        return 1

    # 3. Run Compatibility Fixture Generation (Stage 2)
    try:
        print("\n--- STAGE 2: Parquet to FCN Compatibility Parquet ---")
        cmd = [
            sys.executable,
            str(GLUE_SCRIPTS_DIR / "scripts/dev/make_fourcastnet_compatibility_fixture.py"),
            "--INPUT_PARQUET", str(raw_parquet_path),
            "--OUTPUT_DIR", str(output_dir),
            "--MODE", "compatibility_fixture",
            "--LATITUDE_POLICY", "drop_south_pole",
            "--FORCE",
        ]
        print(f"Executing: {' '.join(cmd)}")
        subprocess.run(cmd, check=True)
        print("Stage 2 completed successfully.")
    except Exception as exc:
        print(f"Stage 2 failed: {exc}", file=sys.stderr)
        return 1

    # 4. Run Tensor Export (Stage 3)
    try:
        print("\n--- STAGE 3: FCN Compatibility Parquet to Tensor ---")
        compat_parquet_path = output_dir / "fcn_compat_20260331_12z.parquet"
        cmd = [
            sys.executable,
            str(GLUE_SCRIPTS_DIR / "scripts/dev/export_fourcastnet_tensor.py"),
            "--INPUT_PARQUET", str(compat_parquet_path),
            "--OUTPUT_DIR", str(output_dir),
            "--LATITUDE_POLICY", "drop_south_pole",
            "--FORCE",
        ]
        print(f"Executing: {' '.join(cmd)}")
        subprocess.run(cmd, check=True)
        print("Stage 3 completed successfully.")
    except Exception as exc:
        print(f"Stage 3 failed: {exc}", file=sys.stderr)
        return 1

    # 5. Run Tensor Validation (Stage 4)
    try:
        print("\n--- STAGE 4: Tensor Validation against Global Stats ---")
        tensor_path = output_dir / "input_tensor.npy"
        means_path = GLUE_SCRIPTS_DIR / "data/fourcastnet_assets_v0/global_means.npy"
        stds_path = GLUE_SCRIPTS_DIR / "data/fourcastnet_assets_v0/global_stds.npy"
        validation_report_path = output_dir / "tensor_validation_report.json"
        cmd = [
            sys.executable,
            str(GLUE_SCRIPTS_DIR / "scripts/dev/validate_fourcastnet_tensor.py"),
            "--INPUT_TENSOR", str(tensor_path),
            "--GLOBAL_MEANS", str(means_path),
            "--GLOBAL_STDS", str(stds_path),
            "--STATS_CHANNEL_POLICY", "first_20_channels",
            "--OUTPUT_REPORT", str(validation_report_path),
        ]
        print(f"Executing: {' '.join(cmd)}")
        subprocess.run(cmd, check=True)
        print("Stage 4 completed successfully.")
    except Exception as exc:
        print(f"Stage 4 failed: {exc}", file=sys.stderr)
        return 1

    # 6. Organize expected files and manifest renames
    try:
        print("\n--- STAGE 5: Manifest Renames and Packaging ---")
        # Rename manifest.json generated by make_fourcastnet_compatibility_fixture to source_manifest.json
        orig_manifest = output_dir / "manifest.json"
        source_manifest = output_dir / "source_manifest.json"
        if orig_manifest.exists():
            shutil.move(str(orig_manifest), str(source_manifest))
            print("Renamed manifest.json to source_manifest.json")

        # Extract channel_order.json from tensor_manifest.json
        tensor_manifest_path = output_dir / "tensor_manifest.json"
        if tensor_manifest_path.exists():
            with open(tensor_manifest_path, "r", encoding="utf-8") as f:
                tensor_manifest = json.load(f)
            channel_order = tensor_manifest.get("channel_order", [])
            with open(output_dir / "channel_order.json", "w", encoding="utf-8") as f:
                json.dump({"channel_order": channel_order}, f, indent=2)
            print("Extracted and saved channel_order.json")
        
        print("Stage 5 completed successfully.")
    except Exception as exc:
        print(f"Stage 5 failed: {exc}", file=sys.stderr)
        return 1

    print("\n=============================================================")
    print("ALL PIPELINE STAGES COMPLETED SUCCESSFULLY!")
    print("=============================================================")
    return 0


if __name__ == "__main__":
    sys.exit(main())
